### ISSUE TITLE
Exception on eval in cljs console

### ISSUE THREAD

**Issue by arichiardi** [binaryage/dirac#30] opened 2016-07-29 20:01 UTC
Here is the issue as discussed on Slack, evaluating *any* form throws:

```
Internal Dirac Error: DevTools code has thrown an unhandled exception
TypeError: Cannot read property 'shift' of undefined
    at WebInspector.ConsoleView._alterDiracViewMessage (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/console_module.js:398:137)
    at WebInspector.ConsoleView._createViewMessage (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/console_module.js:406:133)
    at WebInspector.ConsoleView._addConsoleMessage (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/console_module.js:384:131)
    at WebInspector.ConsoleView._onConsoleMessageAdded (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/console_module.js:380:32)
    at WebInspector.MultitargetConsoleModel.dispatchEventToListeners (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:772:185)
    at WebInspector.MultitargetConsoleModel._consoleMessageAdded (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4613:7)
    at WebInspector.ConsoleModel.dispatchEventToListeners (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:772:185)
    at WebInspector.ConsoleModel.addMessage (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4542:97)
    at WebInspector.DiracAwareConsoleDispatcher.messageAdded (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4596:311)
    at WebInspector.DiracAwareConsoleDispatcher.messageAdded (chrome-extension://kbkdngfljkchidcjpnfcgcokkbhlkogi/devtools/front_end/inspector.js:4604:55)
```

This happens with `0.6.2` and Google Chrome `54.0.2810.2 dev (64-bit)`

**Comment by darwin** [comment] 2016-07-29 20:12
Thanks for reporting. Just to add probably related to Linux only. Seems to work on my Mac 10.11.6.

**Comment by darwin** [comment] 2016-07-29 22:30
Was able to reproduce it under Mac as well. The root cause for this error is protocol mismatch between Chrome ~54.0.2810.2 and embedded DevTools in Dirac Extensions v0.6.2. Version 0.6.2 worked with Chrome  around ~54.0.2793.0.

Unfortunately Chrome is in flux right now due to major debugging protocol changes related to V8 debugging support. This issue will resolve itself with next Dirac release.

**Comment by arichiardi** [comment] 2016-07-29 23:35
Thanks for investigating! Do you think a downgrade would solve?

**Comment by darwin** [comment] 2016-07-30 00:01
I don't know where to get specific versions of Chrome Canary.

I will release a hotfix Dirac over the weekend. I will work with today's Canary (at least for few days :)

**Comment by arichiardi** [comment] 2016-07-30 04:29
Thanks that sound perfect!

**Comment by darwin** [comment] 2016-07-30 12:12
Should be fixed now in [v0.6.3](https://github.com/binaryage/dirac/releases/tag/v0.6.3).

**Closed by darwin** 2016-07-30 12:12 UTC
Labels: bug

**Comment by arichiardi** [comment] 2016-07-31 03:10
I confirm it works:

![selection_013](https://cloud.githubusercontent.com/assets/1724788/17274326/966867d8-5691-11e6-9203-bbf59e187590.png)

**Comment by superstructor** [comment] 2016-07-31 20:14
Confirmed working with Chrome 54.0.2813 on Mac. Thanks!
