### ISSUE TITLE
Is Dirac compatible with namespaces using clojure.spec?

### ISSUE THREAD

**Issue by OliverM** [binaryage/dirac#55] opened 2017-02-13 19:34 UTC
Hi, 

I've just started using Dirac (it looks phenomenal) but it seems to be starting up with some spurious errors that don't seem to impact on execution. 
- The first reads `(unknown) Uncaught SyntaxError: Invalid or unexpected token` with no stack trace (though there is a disclosure triangle).
- The second says `Internal Dirac Error Unable to parse namespace from source` and the stack trace starts with `Dirac v1.1.4, Chrome/58.0.3011.0, Mac/10.12.3, Backend API/external/460, Backend CSS/external/415` before showing the contents of my clojure.spec defintions file in its entirety. In case it's useful, the namespace declaration itself reads:
```clj
An error was logged into the internal DevTools console:
  | Unable to parse namespace from source
  |  (ns vista-fig.specs
  |   (:require [clojure.spec :as s]
  |             #?(:clj [clojure.spec.gen :as gen]
  |                :cljs  [cljs.spec.impl.gen :as gen])
  |             [clojure.spec.test :as test]
  |             #?(:clj [clojure.future :refer :all])))
```
- The third says `Internal Dirac Error :` (e.g. nothing after the colon) followed by a stack-trace, beginning:
```
Dirac v1.1.4, Chrome/58.0.3011.0, Mac/10.12.3, Backend API/external/460, Backend CSS/external/415` 

An error was logged into the internal DevTools console:
  | : {:changed-namespaces {...}
```

I dropped the rest as it seems to be a list of the server-side dependencies I'm using, plus their aliases and other runtime namespace config. I can pass the full text on if you think it's useful; the `:dependencies` entry in my `project.clj` is:
```clj
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.9.229"]
                 [clojure-future-spec "1.9.0-alpha14"]
                 [org.clojure/test.check "0.9.0"]
                 [rum "0.10.5"]
                 [cljsjs/d3 "4.2.2-0"]
                 [hiccup "1.0.5"]
                 [cljs-ajax "0.5.8"]

                 [binaryage/dirac "RELEASE"]

                 ;; persistence
                 [org.clojure/java.jdbc "0.6.2-alpha3"]
                 [com.h2database/h2 "1.4.192"]
                 [honeysql "0.8.1"] ;; runtime sql query generation

                 ;; server
                 [clj-time "0.12.0"]
                 [aleph "0.4.1"]
                 [bidi "2.0.9"]
                 [yada "1.1.37"]]

```

If I can supply any more detail or run any tests let me know.

Thanks again for Dirac, even in my short time using it it's been great.

**Comment by darwin** [comment] 2017-02-13 19:42
Hmm, `:changed-namespaces` looks like this:
https://github.com/binaryage/dirac/issues/52#issuecomment-272444194

I wanted to make Dirac 1.1.4 to print a warning about "foreign" middleware in terminal when launching Dirac Agent. So it looks like [the new code](https://github.com/binaryage/dirac/commit/1c74b7d6230204f4e7570307392cef9dee65875e#diff-de672501dc843559518edf174368158a) didn't trigger.

The `Unable to parse namespace from source` error could be a problem with reader conditionals. I'm using `clojure.tools.namespace` for parsing sources.

**Comment by darwin** [comment] 2017-02-13 19:48
I think the namespace parsing problem is here:
https://github.com/binaryage/dirac/blob/ef88796f814e4f9975f17369ced2261ef4aebe09/src/implant/dirac/implant/analyzer.cljs#L13

I have to instruct `read-ns-decl` to use `cljs-read-opts`:
https://github.com/clojure/tools.namespace/blob/3b8265f4993f5c17317afc2fbfeb3f264362cc75/src/main/clojure/clojure/tools/namespace/parse.cljc#L33

**Comment by OliverM** [comment] 2017-02-15 08:21
Dropping the reader conditionals in the namespace does remove the `Internal Dirac Error Unable to parse namespace from source ` error

**Comment by darwin** [comment] 2017-02-19 00:41
Cannot really tell anything about the first "Uncaught SyntaxError" error.
The reader-conditionals issue will be fixed in the next release 1.1.5.
The third issue is a conflict in with your CIDER middleware (I assume).

Feel free to reopen or create a new issue if you find additional details. You can use internal devtools to inspect Dirac DevTools window to maybe see better errors in internal console, it could help with the first issue: https://github.com/binaryage/dirac/blob/master/docs/faq.md#something-broke-how-do-i-debug-dirac-devtools-frontend

**Closed by darwin** 2017-02-19 00:41 UTC
Labels: bug

**Comment by OliverM** [comment] 2017-02-25 11:31
1.1.5 actually resolves the first two issues for me, leaving only the third which is due to a conflict with CIDER middleware as you point out. 

Dirac now prints a warning in the Chrome inspector about a version mismatch, saying I have 1.1.4 installed, even though I've specifically set the require string to `[binaryage/dirac "1.1.5"]` in my `project.clj` but the namespaces with reader conditionals are read without issue. Thank you so much for resolving this!

**Comment by darwin** [comment] 2017-02-25 15:51
I'm glad the issue is resolved. Thanks for confirmation.

Can you copy and paste the exact version mismatch message? There can be different flavours of them.

https://github.com/binaryage/dirac/blob/master/docs/upgrading.md#understanding-the-release-process

**Comment by OliverM** [comment] 2017-02-25 16:33
Sure, the Chrome console says:

```
Version mismatch: Dirac Runtime installed in your app has different version (v1.1.4) than Dirac Chrome Extension (v1.1.5).
To avoid compatibility issues, please upgrade all Dirac components to the same version: https://github.com/binaryage/dirac/blob/master/docs/upgrading.md.
λ	@	VM321:1
```

Meanwhile, the clojure repl that launches the listener says:
```
Dirac Agent v1.1.5
Connected to nREPL server at nrepl://localhost:8230.
Agent is accepting connections at ws://localhost:8231.
```

**Comment by OliverM** [comment] 2017-02-25 16:33
I ran a `lein clean` before re-launching just in case - no change.

**Comment by darwin** [comment] 2017-02-25 19:14
I can imagine two scenarios:

1) your Canary is using a cached version - hard load should fix it
2) your `lein clean` does not clean the output directory of your cljs-build - this would hint to a misconfiguration in your project.clj

**Comment by OliverM** [comment] 2017-02-25 19:55
The Canary hard reload fixed it. Thanks for the pointers!
